### ISSUE TITLE
OOPF Assignment Feedback

### ISSUE THREAD

**Issue by Pokeanu** [pupubird/WebFundamental2019#6]
The current damage calculation system for the Pokemon mock-up game calculates weakness incorrectly. The current evaluation for weakness is as follows:

Assuming Pokemon A is an Attack-type with color red, and Pokemon B is a Defense-type with color red:

if (
pokemonA.getColor().equals(
pokemonB.getColor()
)
) {
weakness = true; }

This means that, following this formula, although Pokemon A and B are of different types, weakness is enabled. This is a logic error.

The current formula is incorrect, since weakness is true IF the types of the two Pokemon are the same, and not the nature. The current formula uses Pokemon nature instead of Pokemon type.

Please make a small change to the formula:

if (pokemonA.getType().equals(
pokemonB.getType()
)
) {
weakness = true; }

![proof](https://user-images.githubusercontent.com/40918174/69493822-a5823280-0eee-11ea-88a9-7c2bde566a7e.PNG)
This way, weakness is only enabled if the two Pokemon involved in combat are of the same type (ATK vs ATK, DEF vs DEF, etc.).

**Comment by Pokeanu** [comment]
@pupubird here you go

**Comment by pupubird** [comment]
wrong repo

**Comment by pupubird** [comment]
🤔
